// Design review screenshots on seeded data. Usage: node e2e/design-shots.mjs <outDir> [baseUrl]
import { chromium } from 'playwright-core';
import fs from 'node:fs';
import path from 'node:path';
import * as fx from './fixture.mjs';

const OUT = process.argv[2] ?? 'design-shots';
const BASE = process.argv[3] ?? 'http://localhost:5173/';
fs.mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const shot = (n) => page.screenshot({ path: path.join(OUT, `${n}.png`) });

await page.goto(BASE);
await page.evaluate(async () => { indexedDB.deleteDatabase('QuotesDB'); localStorage.clear(); });
await page.reload(); await page.waitForTimeout(800);
await shot('d01-list-empty');
const priced = { ...fx.quote, products: fx.quote.products.map((p, i) => ({ ...p, ...[{ costOff: 5400, totalCost: 6400, sellPrice: 9143, totalValue: 914300 }, { costOff: 810, totalCost: 1110, sellPrice: 1708, totalValue: 854000 }, { costOff: 5040, totalCost: 6540, sellPrice: 8720, totalValue: 436000 }][i] })) };
await fx.seed(page, { providers: fx.providers, quotes: [priced, fx.quote2, { ...fx.quote2, id: 'q3', client: 'Universidad Central', number: '118', date: '2025-08-02' }] });
await page.reload(); await page.waitForTimeout(800);
await shot('d02-list');
await page.getByRole('button', { name: 'Nueva cotización' }).first().click(); await page.waitForTimeout(400);
await shot('d03-new-quote');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Proveedores' }).click(); await page.waitForTimeout(400);
await shot('d04-providers');
await page.getByRole('button', { name: 'Editar PROMOS' }).click(); await page.waitForTimeout(300);
await shot('d05-provider-edit');
await page.keyboard.press('Escape'); await page.keyboard.press('Escape');
await page.goto(BASE + '#/cotizacion/fixq01'); await page.locator('#product-quantity-0').waitFor(); await page.waitForTimeout(500);
await shot('d06-editor');
await page.locator('#product-provider-2').click(); await page.waitForTimeout(300);
await shot('d07-provider-dropdown');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Detalles fila 1' }).click(); await page.waitForTimeout(400);
await shot('d08-details');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Ajustes del PDF' }).click(); await page.waitForTimeout(300);
await shot('d09-pdf-settings');
await page.evaluate(() => { const ps = JSON.parse(localStorage.getItem('providers')); localStorage.setItem('providers', JSON.stringify(ps.map(p => (p.name === 'PROMOS' ? { ...p, discount: 0.35 } : p)))); window.dispatchEvent(new Event('providersUpdated')); });
await page.waitForTimeout(300);
await shot('d10-notice');
await page.setViewportSize({ width: 390, height: 844 });
await page.goto(BASE); await page.waitForTimeout(600);
await page.screenshot({ path: path.join(OUT, 'd11-mobile-list.png'), fullPage: true });
await page.goto(BASE + '#/cotizacion/fixq01'); await page.locator('#product-quantity-0').waitFor(); await page.waitForTimeout(400);
await shot('d12-mobile-editor');
console.log(JSON.stringify({ errors }));
await browser.close();
